import numpy as np
from scipy.io.wavfile import write
from IPython.display import Audio # This was used to display the audio inside of the Jupyter Notebook

# The code here assumes that you have two arrays already created: predictedf0, and f0Time, which should be generated by a model. predictedf0 corresponds to the 
# a model's predicted sequence of pitches representing the extracted melody contours. f0Time is the timestamp at which each pitch prediction corresponds to.

f0 = np.nan_to_num(predictedf0, nan=0.0).astype(float)
voiced_frames = f0 > 100.0
f0[~voiced_frames] = 0.0

duration_sec = f0Time[-1]
sample_times = np.arange(int(duration_sec * sr)) / sr

voiced_interp = np.interp(
    sample_times, f0Time, voiced_frames.astype(float)
)
voiced_mask = voiced_interp >= 0.5

if np.any(voiced_frames):
    phase_f0 = np.interp(
        sample_times, f0Time[voiced_frames], f0[voiced_frames]
    )
else:
    phase_f0 = np.zeros_like(sample_times)

raw_audio = np.zeros_like(sample_times)
amplitude_env = np.zeros_like(sample_times)
fade_samples = int(sr * 0.010)

voicing_edges = np.diff(
    np.pad(voiced_mask.astype(np.int8), (1, 1), constant_values=0)
)
voiced_starts = np.flatnonzero(voicing_edges == 1)
voiced_ends = np.flatnonzero(voicing_edges == -1)

for start, end in zip(voiced_starts, voiced_ends):
    segment_f0 = phase_f0[start:end]
    segment_phase = np.zeros_like(segment_f0)
    if len(segment_f0) > 1:
        segment_phase[1:] = (
            2 * np.pi * np.cumsum(segment_f0[:-1]) / sr
        )

    segment_env = np.ones_like(segment_f0)
    segment_fade = min(fade_samples, len(segment_f0) // 2)
    if segment_fade > 1:
        fade = 0.5 - 0.5 * np.cos(
            np.linspace(0.0, np.pi, segment_fade)
        )
        segment_env[:segment_fade] *= fade
        segment_env[-segment_fade:] *= fade[::-1]
    elif segment_fade == 1:
        segment_env[0] = 0.0
        segment_env[-1] = 0.0

    raw_audio[start:end] = np.sin(segment_phase)
    amplitude_env[start:end] = segment_env

audio = raw_audio * amplitude_env

max_val = np.max(np.abs(audio))
if max_val > 0:
    audio *= 0.98 / max_val

write("PredictedMelodyF0Song.wav", sr, audio.astype(np.float32))
Audio("PredictedMelodyF0Song.wav")
